# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_card', '0002_auto_20180115_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselgalleryimage',
            options={'verbose_name': '갤러리 이미지', 'verbose_name_plural': '갤러리 이미지'},
        ),
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'verbose_name': '이미지 스와이프 청첩장', 'verbose_name_plural': '이미지 스와이프 청첩장(메인)'},
        ),
        migrations.AlterModelOptions(
            name='carouselsmsimage',
            options={'verbose_name': '2G 핸드폰공유 이미지', 'verbose_name_plural': '2G 핸드폰공유 이미지'},
        ),
        migrations.RemoveField(
            model_name='carouselimage',
            name='massage_image15',
        ),
    ]
