# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_card', '0003_auto_20180115_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image10_explain',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image10_name',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image1_explain',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image1_name',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image2_explain',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image2_name',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image3_explain',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image3_name',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image4_explain',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image4_name',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image5_explain',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image5_name',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image6_explain',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image6_name',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image7_explain',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image7_name',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image8_explain',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image8_name',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image9_explain',
        ),
        migrations.RemoveField(
            model_name='carouselgalleryimage',
            name='image9_name',
        ),
    ]
