# Generated by Django 2.0.1 on 2018-01-22 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_card', '0004_auto_20180117_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselgalleryimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carousel_card.CarouselImage'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carouselsmsimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carousel_card.CarouselImage'),
        ),
    ]
