# Generated by Django 2.0.1 on 2018-01-23 05:33

import carousel_card.models
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_card', '0006_samplecarouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleCarouselGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('gallery_image1', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=carousel_card.models.get_image_path)),
                ('gallery_image2', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=carousel_card.models.get_image_path)),
                ('gallery_image3', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=carousel_card.models.get_image_path)),
                ('gallery_image4', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=carousel_card.models.get_image_path)),
                ('gallery_image5', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=carousel_card.models.get_image_path)),
                ('gallery_image6', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=carousel_card.models.get_image_path)),
                ('gallery_image7', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=carousel_card.models.get_image_path)),
                ('gallery_image8', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=carousel_card.models.get_image_path)),
                ('gallery_image9', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=carousel_card.models.get_image_path)),
                ('gallery_image10', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=carousel_card.models.get_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carousel_card.SampleCarouselImage')),
            ],
            options={
                'verbose_name': '갤러리 이미지',
                'verbose_name_plural': '갤러리 이미지',
            },
        ),
        migrations.CreateModel(
            name='SampleCarouselSmsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message_image1', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=carousel_card.models.get_image_path)),
                ('message_image2', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=carousel_card.models.get_image_path)),
                ('message_image3', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=carousel_card.models.get_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carousel_card.SampleCarouselImage')),
            ],
            options={
                'verbose_name': '2G 핸드폰공유 이미지',
                'verbose_name_plural': '2G 핸드폰공유 이미지',
            },
        ),
    ]
