# Generated by Django 2.0.1 on 2018-01-23 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_card', '0007_samplecarouselgalleryimage_samplecarouselsmsimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplecarouselgalleryimage',
            options={'verbose_name': '(샘플)갤러리 이미지', 'verbose_name_plural': '(샘플)갤러리 이미지'},
        ),
        migrations.AlterModelOptions(
            name='samplecarouselsmsimage',
            options={'verbose_name': '(샘플)2G 핸드폰공유 이미지', 'verbose_name_plural': '(샘플)2G 핸드폰공유 이미지'},
        ),
    ]
