# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 02:49
from __future__ import unicode_literals

import card.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_auto_20170814_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image10',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image11',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image12',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image13',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image14',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image15',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image16',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image5',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image6',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image7',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image8',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path),
        ),
        migrations.AddField(
            model_name='post',
            name='image9',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path),
        ),
    ]
