# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_auto_20170816_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='call1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='call2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
