# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_post_kakao_link_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='youtube_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='kakao_link_label',
            field=models.TextField(max_length=500),
        ),
    ]
