# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_auto_20170820_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ohoystdio_url',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
