# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_post_ohoystdio_img_src_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ohoystdio_img_src_url',
            new_name='ohoystudio_img_src_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ohoystdio_url',
        ),
        migrations.AddField(
            model_name='post',
            name='ohoystudio_url',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
