# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_auto_20170824_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image1',
            new_name='call1_image4',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image10',
            new_name='call2_image5',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image11',
            new_name='celendar_image6',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image12',
            new_name='copyright_image16',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image13',
            new_name='facebook_image14',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image14',
            new_name='family_image3',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image15',
            new_name='gallery_image7',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image16',
            new_name='invitation_image2',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image2',
            new_name='kakao_image12',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image3',
            new_name='main_image1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image4',
            new_name='map_image9',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image5',
            new_name='map_infor_image10',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image6',
            new_name='massage_image15',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image7',
            new_name='message_title_image11',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image8',
            new_name='story_image13',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image9',
            new_name='videotitle_image8',
        ),
    ]
