# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_remove_post_ohoystudio_img_src_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='comment',
            name='password2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
