# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0017_auto_20170908_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='password2',
            field=models.CharField(max_length=50),
        ),
    ]
