# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 11:56
from __future__ import unicode_literals

import card.models
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0018_auto_20170908_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message_image1', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path)),
                ('message_image2', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path)),
                ('message_image3', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Post')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='password2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
