# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 12:20
from __future__ import unicode_literals

import card.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0019_auto_20170915_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kakao_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path),
        ),
    ]
