# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0022_auto_20171207_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='password2',
        ),
    ]
