# Generated by Django 2.0.1 on 2018-01-23 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0023_auto_20171215_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '댓글', 'verbose_name_plural': '댓글'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '댓글있는 청첩장', 'verbose_name_plural': '댓글있는 청첩장(메인)'},
        ),
        migrations.AlterModelOptions(
            name='postgallery',
            options={'verbose_name': '갤러리', 'verbose_name_plural': '갤러리'},
        ),
        migrations.AlterModelOptions(
            name='smsimage',
            options={'verbose_name': '2G 핸드폰공유 이미지', 'verbose_name_plural': '2G 핸드폰공유 이미지'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='massage_image15',
        ),
        migrations.AddField(
            model_name='comment',
            name='password2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card.Post'),
        ),
        migrations.AlterField(
            model_name='smsimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card.Post'),
        ),
    ]
