# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-09 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0023_auto_20171215_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='password2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
