# Generated by Django 2.0.1 on 2018-01-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0026_auto_20180122_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplepost',
            options={'verbose_name': '댓글있는 청첩장(샘플)', 'verbose_name_plural': '댓글있는 청첩장(샘플)'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='message_title_image11',
        ),
        migrations.AlterField(
            model_name='samplepost',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
