# Generated by Django 2.0.1 on 2018-01-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0027_auto_20180122_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplepost',
            name='post_ptr',
        ),
        migrations.DeleteModel(
            name='SamplePost',
        ),
    ]
