# Generated by Django 2.0.1 on 2018-01-22 07:53

import card.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0030_post_message_title_image11'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplepost',
            name='message_title_image11',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card.models.get_image_path),
        ),
    ]
