# Generated by Django 2.0.1 on 2018-01-22 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0031_samplepost_message_title_image11'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sample_post',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='card.SamplePost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postgallery',
            name='sample_post',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='card.SamplePost'),
            preserve_default=False,
        ),
    ]
