# Generated by Django 2.0.1 on 2018-01-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0033_auto_20180122_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplecomment',
            options={'verbose_name': '(샘플)댓글', 'verbose_name_plural': '(샘플)댓글'},
        ),
        migrations.AlterModelOptions(
            name='samplepostgallery',
            options={'verbose_name': '(샘플)갤러리', 'verbose_name_plural': '(샘플)갤러리'},
        ),
        migrations.AlterModelOptions(
            name='samplesmsimage',
            options={'verbose_name': '(샘플)2G 핸드폰공유 이미지', 'verbose_name_plural': '(샘플)2G 핸드폰공유 이미지'},
        ),
    ]
