# Generated by Django 2.0.1 on 2018-01-23 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0034_auto_20180122_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplecomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card.SamplePost'),
        ),
        migrations.AlterField(
            model_name='samplepostgallery',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card.SamplePost'),
        ),
        migrations.AlterField(
            model_name='samplesmsimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card.SamplePost'),
        ),
    ]
