# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postnotcomment',
            old_name='ohoystdio_img_src_url',
            new_name='ohoystudio_img_src_url',
        ),
        migrations.RenameField(
            model_name='postnotcomment',
            old_name='ohoystdio_url',
            new_name='ohoystudio_url',
        ),
    ]
