# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 12:23
from __future__ import unicode_literals

import card2.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('card2', '0003_auto_20170825_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='postnotcomment',
            name='kakao_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=card2.models.get_image_path),
        ),
    ]
