# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card2', '0007_postgallery2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostGallery',
            new_name='GalleryImage',
        ),
        migrations.RenameModel(
            old_name='PostNotComment',
            new_name='InfomationImage',
        ),
        migrations.RenameModel(
            old_name='PostGallery2',
            new_name='SmsImage',
        ),
    ]
