# Generated by Django 2.0.1 on 2018-01-22 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card2', '0010_auto_20180115_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card2.InfomationImage'),
        ),
        migrations.AlterField(
            model_name='infomationimage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='smsimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card2.InfomationImage'),
        ),
    ]
