# Generated by Django 2.0.1 on 2018-01-23 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card2', '0013_auto_20180123_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplegalleryimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card2.SampleInfomationImage'),
        ),
        migrations.AlterField(
            model_name='samplesmsimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card2.SampleInfomationImage'),
        ),
    ]
