# Generated by Django 2.0.1 on 2018-01-23 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card2', '0014_auto_20180123_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplegalleryimage',
            options={'verbose_name': '(샘플)갤러리', 'verbose_name_plural': '(샘플)갤러리'},
        ),
        migrations.AlterModelOptions(
            name='samplesmsimage',
            options={'verbose_name': '(샘플)2G 핸드폰공유 이미지', 'verbose_name_plural': '(샘플)2G 핸드폰공유 이미지'},
        ),
    ]
